In [1]:
      ######### Session – 10 ##########################
# Task 1: Memory Layout & Summation Speed Comparison

import numpy as np
import time
import sys

# Number of elements
n = 1_000_000

# Create a Python list
python_list = list(range(n))

# Create an equivalent NumPy array
numpy_array = np.arange(n, dtype=np.int64)

print("Number of elements:", n)
print("First 5 values:", python_list[:5])
print("Last 5 values:", python_list[-5:])

# Memory used by the list object itself
list_object_size = sys.getsizeof(python_list)

# Memory used by the individual integer objects inside the list
list_element_memory = sum(sys.getsizeof(x) for x in python_list)

# Estimated total memory used by the Python list
total_list_memory = list_object_size + list_element_memory

# NumPy array memory
# nbytes gives the size of the actual numerical data buffer
numpy_memory = numpy_array.nbytes

print(f"Python list object memory: {list_object_size:,} bytes")
print(f"Python list element memory: {list_element_memory:,} bytes")
print(f"Python list total estimated memory: {total_list_memory:,} bytes")
print(f"NumPy array memory: {numpy_memory:,} bytes")

memory_ratio = total_list_memory / numpy_memory

print(f"\nPython list memory: {total_list_memory:,} bytes")
print(f"NumPy array memory: {numpy_memory:,} bytes")
print(f"List uses approximately {memory_ratio:.2f} times more memory.")

# Measure Python list sum
start_time = time.perf_counter()

list_sum = sum(python_list)

list_time = time.perf_counter() - start_time


# Measure NumPy array sum
start_time = time.perf_counter()

numpy_sum = numpy_array.sum()

numpy_time = time.perf_counter() - start_time


print(f"Python list sum: {list_sum}")
print(f"NumPy array sum: {numpy_sum}")

print(f"\nTime using Python list: {list_time:.6f} seconds")
print(f"Time using NumPy array: {numpy_time:.6f} seconds")

print("----- Final Comparison -----")
print(f"Python list memory : {total_list_memory:,} bytes")
print(f"NumPy array memory : {numpy_memory:,} bytes")

print(f"\nPython list sum time : {list_time:.6f} seconds")
print(f"NumPy array sum time : {numpy_time:.6f} seconds")

if numpy_time > 0:
    print(f"\nNumPy sum is approximately {list_time / numpy_time:.2f} times faster.")

Number of elements: 1000000
First 5 values: [0, 1, 2, 3, 4]
Last 5 values: [999995, 999996, 999997, 999998, 999999]
Python list object memory: 8,000,056 bytes
Python list element memory: 28,000,000 bytes
Python list total estimated memory: 36,000,056 bytes
NumPy array memory: 8,000,000 bytes

Python list memory: 36,000,056 bytes
NumPy array memory: 8,000,000 bytes
List uses approximately 4.50 times more memory.
Python list sum: 499999500000
NumPy array sum: 499999500000

Time using Python list: 0.005511 seconds
Time using NumPy array: 0.000674 seconds
----- Final Comparison -----
Python list memory : 36,000,056 bytes
NumPy array memory : 8,000,000 bytes

Python list sum time : 0.005511 seconds
NumPy array sum time : 0.000674 seconds

NumPy sum is approximately 8.18 times faster.


In [2]:
#Task 2: Array Creation and Shaping
#Analogy: Imagine laying out a city block grid or constructing a skyscraper floor by floor. You
#will use different NumPy functions to build various array “structures.”
#Instructions: Perform the following steps using NumPy array creation routines:
#1. Convert a Python list to an array: Given a list of 12 city block IDs block_ids =
#[101, 102, …, 112], create a 1D NumPy array.
#2. Create a zero matrix and modify it: Use np.zeros to create a 3×3 matrix of zeros
#(dtype int). Then set the diagonal elements to 255 (e.g., like an identity matrix scaled by 255).
#3. Generate a range of values: Use np.arange to create a 1D array of integers from 10 to
#50 (inclusive) with step 10. Then reshape it into a 2D array with 3 rows.
#4. Interpolate values with linspace: Use np.linspace to generate an array of 7 values
#evenly spaced from 0 to 1.
#Input: Values are specified in the steps (no external input file).

import numpy as np

# City block IDs
block_ids = [101, 102, 103, 104, 105, 106,
             107, 108, 109, 110, 111, 112]

# Convert Python list to a 1D NumPy array
block_array = np.array(block_ids)

print("Original Python list:")
print(block_ids)

print("\n1D NumPy array:")
print(block_array)

print("\nShape:", block_array.shape)
print("Dimension:", block_array.ndim)

Original Python list:
[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112]

1D NumPy array:
[101 102 103 104 105 106 107 108 109 110 111 112]

Shape: (12,)
Dimension: 1


In [3]:
#Task 3: Broadcasting Operations
#Analogy: Broadcasting in NumPy is like sending a single radio signal to multiple receivers. You
#will automatically “broadcast” a smaller array across a larger one according to NumPy’s rules.
#Instructions: Consider the following scenario: A company has daily base salaries for 3
#employees over 4 days in a 3×4 array base_pay. There is also a 1×4 row vector daily_bonus of
#bonuses (one bonus amount for each day). Use NumPy broadcasting to add the daily bonus to
#each employee’s base pay without writing an explicit loop.
#Example data to use:
#base_pay = np.array([[100, 100, 100, 100],
#[200, 200, 200, 200],
#[300, 300, 300, 300]])
#daily_bonus = np.array([10, 20, 30, 40])
#Compute total_pay = base_pay + daily_bonus using broadcasting.
#Explain briefly: Why this operation works (mention that 1×4 is broadcast to 3×4 per rules).
#Input: The arrays base_pay and daily_bonus as above.

import numpy as np

# Base salaries for 3 employees over 4 days
base_pay = np.array([
    [100, 100, 100, 100],
    [200, 200, 200, 200],
    [300, 300, 300, 300]
])

# Bonus for each day
daily_bonus = np.array([10, 20, 30, 40])

print("Base Pay:")
print(base_pay)

print("\nDaily Bonus:")
print(daily_bonus)

print("\nBase Pay shape:", base_pay.shape)
print("Daily Bonus shape:", daily_bonus.shape)
# NumPy automatically broadcasts daily_bonus across all 3 employees
total_pay = base_pay + daily_bonus

print("Total Pay:")
print(total_pay)
print("Result shape:", total_pay.shape)
print("Result data type:", total_pay.dtype)

Base Pay:
[[100 100 100 100]
 [200 200 200 200]
 [300 300 300 300]]

Daily Bonus:
[10 20 30 40]

Base Pay shape: (3, 4)
Daily Bonus shape: (4,)
Total Pay:
[[110 120 130 140]
 [210 220 230 240]
 [310 320 330 340]]
Result shape: (3, 4)
Result data type: int64


In [7]:
# Task 4: Vectorized Conditional Computation

import numpy as np

readings = np.array([-2, -1, 0, 1, 2])

results = np.where(readings >= 0, readings ** 2, readings ** 3)

print("Original readings:")
print(readings)

print("\nTransformed results:")
print(results)

# Explanation:
# np.where() performs the condition on the entire array without using an explicit Python loop.

# Negative values are cubed:
# -2^3 = -8
# -1^3 = -1
#
# Non-negative values are squared:
# 0^2 = 0
# 1^2 = 1
# 2^2 = 4

Original readings:
[-2 -1  0  1  2]

Transformed results:
[-8 -1  0  1  4]


In [9]:
import numpy as np

scores = np.loadtxt(
    "scores.csv",
    delimiter=",",
    skiprows=1,
    usecols=(1, 2, 3)
)

print(scores)

import os

print(os.getcwd())

[[80. 90. 75.]
 [70. 85. 60.]
 [90. 95. 80.]]
d:\job_training_project


In [ ]:
# Task 5: Real Data Loading and Normalization

import numpy as np

try:
    data = np.genfromtxt(r"D:\job_training_project\scores.csv", delimiter=",", skip_header=1, usecols=(1,2,3))
    
    means = data.mean(axis=0)
    stds = data.std(axis=0)
    
    normalized = (data - means) / stds
    print("Normalized scores:\n", normalized)

except FileNotFoundError:
    print("Error: scores.csv not found in the specified path!")


Normalized scores:
 [[ 0.      0.      0.3922]
 [-1.2247 -1.2247 -1.3728]
 [ 1.2247  1.2247  0.9806]]
